spring:
  application:
    name: jojopay
  cloud:
    aws:
      region:
        static: ap-northeast-2
  profiles:
    active: local

portone:
  secret-key: "MP42bGdUPcTmnU98YXpWCEtLBP26DUqU1WATn20ipyW2HcL3BBwrx7V7nTFQJRPa3V3bbTVKFZjpWxLT"
  api-url: "https://api.portone.io"

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:jojopay_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    # 테스트를 위한 세팅
    defer-datasource-initialization: true # Hibernate가 테이블을 다 만든 후에 data.sql을 실행하도록 지연시킴

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect # H2 방언 사용
  # 테스트를 위한 세팅
  sql:
    init:
      mode: always # 항상 data.sql 스크립트를 실행

jwt:
  secret-key: localEnvDummySecretKeyForJojoPayProjectTest12345!
  access-token-valid-time: 36000000

---

spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/config/jojopay/
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Seoul

# 서버 설정 추가
server:
  address: 0.0.0.0 # 외부에서 접속 가능하게 함
  port: 8080

jwt:
  access-token-valid-time: 3600000